Add 2023 recap page
rubyunconfeu/2023-website pull request #31
Opened 2024-01-04 13:49 UTC by alster-wasser

Added a page with a recap of the 2023 Unconf so we can link to it on the 2024 website.

2024-01-04 13:56 UTC, stefan-evernest requested changes

2024-01-04 13:56 UTC, stefan-evernest commented on assets/recap/christian.png
issue: we should convert photos as JPG for better compression

2024-01-04 13:56 UTC, stefan-evernest commented on assets/recap/team.jpeg
nitpick: we should use the common `jpg` file extension for JPEGs to have a common file naming

2024-01-04 13:56 UTC, stefan-evernest commented on assets/recap/team.jpeg
issue: please resize images to a common size and apply a good compression ratio to not waste visitors bandwidth and allow faster page loading. (we don't need full resolutions for article pictures)

2024-01-10 15:01 UTC, emrox approved these changes

2024-01-11 09:09 UTC, merged